general_config:
    search: "GridSearchCV"
    model: "SGDClassifier"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    random_state: 42
search_config:
    param_grid:
        alpha: [0.0001, 0.001, 0.01]
        loss: ["hinge", "log_loss"]
    scoring: "accuracy" # "f1"
    n_jobs:
    #refit: True
    cv: 10
    verbose: 0
    return_train_score: False

    
    