general_config:
    model: "DecisionTreeClassifier"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    criterion: "gini"
    splitter: "best"
    max_depth: 
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 
    random_state: 42
    max_leaf_nodes: 
    min_impurity_decrease: 0.0
    class_weight: 
    ccp_alpha: 0.0

