general_config:
    model: "KNeighborsClassifier"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    n_neighbors: 5
    weights: "uniform"
    algorithm: "auto"
    leaf_size: 30
    p: 2
    metric: "minkowski"
    metric_params: 
    n_jobs: 