general_config:
    model: "PassiveAggressiveClassifier"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    C: 1.0
    fit_intercept: True
    max_iter: 1000
    tol: 1.0e-3
    early_stopping: False
    validation_fraction: 0.1
    n_iter_no_change: 5
    shuffle: True
    verbose: 0
    loss: "hinge"
    n_jobs: 
    random_state: 42
    warm_start: False
    class_weight: 
    average: False

