general_config:
    model: "SGDClassifier"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    loss: "hinge"
    penalty: "l2"
    alpha: 0.0001
    l1_ratio: 0.15
    fit_intercept: True
    max_iter: 1000
    tol: 1.0e-3
    shuffle: True
    verbose: 0
    epsilon: 0.1
    n_jobs: 
    random_state: 42
    learning_rate: "optimal"
    eta0: 0.0
    power_t: 0.5
    early_stopping: False
    validation_fraction: 0.1
    n_iter_no_change: 5
    class_weight:
    warm_start: False
    average: False


