general_config:
    model: "SVC"
    dataset: "digit"
    root_log_dir: "./results"
model_config:
    C: 1.0
    kernel: "rbf"
    degree: 3
    gamma: "scale"
    coef0: 0.0
    shrinking: True
    probability: False
    tol: 1.0e-3
    cache_size: 200
    class_weight: 
    verbose: False
    max_iter: -1
    decision_function_shape: "ovr"
    break_ties: False
    random_state: 42

